export const SUCCESS_CODES = {
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
  USER_CREATED: 'USER_CREATED',
  USER_UPDATED: 'USER_UPDATED',
  USER_DEACTIVATED: 'USER_DEACTIVATED',
  QR_REGENERATED: 'QR_REGENERATED',
  EVENT_CREATED: 'EVENT_CREATED',
  EVENT_UPDATED: 'EVENT_UPDATED',
  EVENT_STATUS_UPDATED: 'EVENT_STATUS_UPDATED',
  EVENT_DELETED: 'EVENT_DELETED',
  ATTENDANCE_CREATED: 'ATTENDANCE_CREATED',
  ATTENDANCE_UPDATED: 'ATTENDANCE_UPDATED',
  ATTENDANCE_DELETED: 'ATTENDANCE_DELETED',
  CHECK_IN_SUCCESS: 'CHECK_IN_SUCCESS',
  CHECK_OUT_SUCCESS: 'CHECK_OUT_SUCCESS',
} as const;

export type SuccessCode = (typeof SUCCESS_CODES)[keyof typeof SUCCESS_CODES];
